### ISSUE TITLE
are there any special purposes of having empty pkg extensions? 

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedVI.jl#100]
see, e.g.: https://github.com/TuringLang/AdvancedVI.jl/blob/master/ext/AdvancedVIMooncakeExt.jl

**Comment by Red-Portal** [comment]
Yes, it's because Julia's pre-weakdeps system require having at least extras to have a compat bound. So the empty extras could be discarded as soon as we drop pre-1.9 support.

**Comment by Red-Portal** [comment]
This was due to a misunderstanding :sweat_smile:. I removed the empty extensions now
