### ISSUE TITLE
Improving mechanism for updating parameters of distributions

### ISSUE THREAD

**Issue by torfjelde** [TuringLang/AdvancedVI.jl#18]
# Current impl
We need to be able to map parameters to a new distribution with new parameters in a non-mutating manner. Currently there are two options for a user:
1. Provide the mapping `θ ↦ D( ⋅ ; θ)` directly as a function.
2. Overload `AdvancedVI.update(d::MyDistribution, θ...)`.

## Option (1)
From our perspective, (1) is of course the best since it's trivial to work with internally. One issue: it's easy for the user to do it "wrong", e.g. entire `vi` call becomes type-unstable becomes user closes over a global variable pointing to the distibution they want to update, or they do it in a mutation fashion, etc.

## Option (2)
From a user-perspective it's generally nicer to work with (2), where the user essentially provides the initial parameters / variational approximation and then it's left to AdvancedVI to optimize. But there are a couple of reasons why this approach sort of sucks:
1. Different packages overloading in different ways will quickly lead to issues.
2. User essentially have to do it on a case-by-case basis (unless they come up with some clever and likely hacky solution). This is more of an "issue" with Distributions.jl though, i.e. there's no easy way (as far as I'm aware) to reconstruct an arbitrary distribution with a new set of parameters.

# Possible solution (thanks to @devmotion)
Ref: https://github.com/TuringLang/Turing.jl/pull/1377#discussion_r471480894

In AVI we define a default impl of `update` *but* instead of making the overload this method, we make them pass the method as an argument to `vi` and subsequent functions. E.g.
```julia
vi(model, alg) = vi(AdvancedVI.update, model, alg)
function vi(updater, model, alg)
    # Do as we do now, but replace `AdvancedVI.update` with `updater`
    ...
end
```
This way, packages depending on AVI (e.g. Turing.jl), can choose between making their own update-function and passing this into `vi` OR make use of a default impl `AdvancedVI.update` that we provide. And similarily, if the user knows what they're doing, they can provide the `updater` directly.

Issue: annoying to have to pass this `updater` around internally, but oh well.

## Default impl
As a default impl I have the following in mind (though it's imo a bit nasty):
```julia
@generated function update(d::Distribution, θ...)
    return :($(esc(nameof(d)))(θ...))
end
```

EDIT: thanks to @devmotion, this is much improved:
```julia
# Ref: https://github.com/SciML/DiffEqBase.jl/blob/8e1a627d10ec40a112460860cd13948cc0532c63/src/utils.jl#L73-L75
using Base: typename

Base.@pure __parameterless_type(T) = typename(T).wrapper
parameterless_type(x) = parameterless_type(typeof(x))
parameterless_type(x::Type) = __parameterless_type(x)

AdvancedVI.update(d::Distribution, θ...) = parameterless_type(d)(θ...)
```

Ideally we'd have access to the fieldnames for each `Distribution` and `θ` would be a `NamedTuple`. Then we could have used `merge` to combine existing parameters already present in `d` and the new parameters `θ`. Unfortunately, such does not exist in Distributions.jl at the moment, hence we're left with the above hack :confused:

**Comment by devmotion** [comment]
A (similar) approach to the default implementation you outlined above is used by `DiffEqBase.remake`. I imagine that https://github.com/SciML/DiffEqBase.jl/blob/8e1a627d10ec40a112460860cd13948cc0532c63/src/utils.jl#L73-L75 could be useful as well.

**Comment by torfjelde** [comment]
Sick, so default impl can then be:
```julia
using Base: typename

Base.@pure __parameterless_type(T) = typename(T).wrapper
parameterless_type(x) = parameterless_type(typeof(x))
parameterless_type(x::Type) = __parameterless_type(x)

AdvancedVI.update(d::Distribution, θ...) = parameterless_type(d)(θ...)
```

**Comment by Red-Portal** [comment]
I'll close this issue in favor of #46
