### ISSUE TITLE
VI+PSIS

### ISSUE THREAD

**Issue by ParadaCarleton** [TuringLang/AdvancedVI.jl#28]
I've implemented PSIS [here](https://github.com/ParadaCarleton/ParetoSmooth.jl), in case anyone is interested in adding VI+PSIS to Turing (the way it's been added to Stan). VI+PSIS should result in better inference, since VI+PSIS is theoretically consistent, unlike VI alone. More importantly, it provides a good diagnostic, the Pareto shape constant `k`, which lets the user know when VI+PSIS has failed -- large Pareto shape constants indicate the VI algorithm has failed to provide a good approximation to the posterior.

Let me know if you guys need any help.

**Comment by Red-Portal** [comment]
Are you talking about using PSIS to refine the samples from `q`? If that is the case, I think this can be easily done without changing `AdvancedVI.jl` I do have interest in using PSIS as a diagnostic for VI though.
