### ISSUE TITLE
Stein Variational Gradient Descent (SVGD)

### ISSUE THREAD

**Issue by nickrobinson251** [TuringLang/AdvancedVI.jl#3]
Liu, Qiang, and Dilin Wang. "Stein variational gradient descent: A general purpose bayesian inference algorithm." Advances in neural information processing systems. 2016. (https://papers.nips.cc/paper/6338-stein-variational-gradient-descent-a-general-purpose-bayesian-inference-algorithm)

I think both @wesselb and @aisopous have played around with implementing this in Julia :)

**Comment by theogf** [comment]
I started implementing it and will release a PR once it is ready enough

**Comment by ParadaCarleton** [comment]
@theogf any progress?

**Comment by Red-Portal** [comment]
At this point, I think it would be better to have particle VI methods in their own package.
