### ISSUE TITLE
Run benchmarking only on PRs

### ISSUE THREAD

**Issue by yebai** [TuringLang/AdvancedVI.jl#74]
@shravanngoswamii In addition, we also need an option in NavBar bash script to skip a folder under gh-pages.

**Comment by shravanngoswamii** [comment]
> @shravanngoswamii In addition, we also need an option in NavBar bash script to skip a folder under gh-pages.

Only for this package or all packages?

**Comment by shravanngoswamii** [comment]
> For all packages if possible, but this should be an optional argument to the bash script if possible, so we don't need to update places where not needed.

Sure, I will update the script soon!
