### ISSUE TITLE
Make use of DifferentiationInterface.jl?

### ISSUE THREAD

**Issue by willtebbutt** [TuringLang/AdvancedVI.jl#85]
Currently, there are extensions for each of the AD backends that this package supports. Would it be possibe to refactor to just make use of DifferentiationInterface, and let the user swap out the `ADType` so that we don't have to maintain this here?

**Comment by Red-Portal** [comment]
I would love to, but we heavily make use of auxiliary input which requires [this issue](https://github.com/gdalle/DifferentiationInterface.jl/issues/311) to be resolved.

**Comment by willtebbutt** [comment]
Ahhh makes sense. I'll close this issue since it seems like you're on top of it!

**Comment by Red-Portal** [comment]
@gdalle Absolutely! Do you have a rough release date in mind?

**Comment by Red-Portal** [comment]
Handled by #98
