### ISSUE TITLE
Currently no license

### ISSUE THREAD

**Issue by millerjoey** [TuringLang/AdvancedVI.jl#9]
Hi! I noticed there's no license on this project. I assume/hope the [MIT license](https://github.com/TuringLang/NestedSamplers.jl/blob/master/LICENSE) on the related Turing projects is applicable.

**Comment by yebai** [comment]
yes, it should be MIT licensed, similar to other Turing libraries. 

cc @torfjelde

**Comment by torfjelde** [comment]
Ah, thanks @millerjoey ! Got it sorted out:)

**Comment by millerjoey** [comment]
Great, thanks guys!
